# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://parels.gelovenleren.net
title: Parels van het Katholieke Geloof
email: info@gelovenleren.net
author: Geloven Leren
description: > # "Write an awesome description for your new site here. 
  Parels van het Katholieke Geloof is een boek dat in veertien korte
  hoofdstukken een bloemlezing brengt van het rijke rooms-katholieke
  geloofsleven. Het streeft geen volledigheid na en is evenmin opgebouwd
  volgens een bepaald programma, maar het laat enkele facetten oplichten van
  het katholieke geloof die vaak onderbelicht blijven. Het is geschreven
  voor jongeren die na hun vormsel bereid zijn hun geloof verder te
  ontwikkelen. Sommige hoofdstukken vereisen meer achtergrondkennis, dus
  het zou ideaal zijn als de ouders aan de lectuur deelnemen en erover met
  hun kinderen in dialoog treden, in de hoop dat het hen aanspoort om zelf
  ook naar nieuwe facetten van het geloof op zoek te gaan. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github:
  url: http://localhost:4000
twitter_username: vicmortelmans
github_username: vicmortelmans 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/alledaagsgeloven/
  - title: inbox
    url: http://eepurl.com/9P0gP
